version: '3.8'
services:
  firebase-emulators:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    container_name: firebase_emulators
    ports:
      - "4000:4000" # Emulator Suite UI
      - "8080:8080" # Firestore Emulator
      - "9099:9099" # Auth Emulator
      - "5001:5001" # Functions Emulator
      - "5000:5000" # Hosting Emulator
    command: >
      bash -c "firebase emulators:start --project=damdoh-local --import=/opt/firebase/data --export-on-exit=/opt/firebase/data"
    volumes:
      - ./firebase_data:/opt/firebase/data
    environment:
      - FIRESTORE_PROJECT_ID=damdoh-local
      - GCLOUD_PROJECT=damdoh-local

volumes:
  firebase_data:
